sudo: required
services:
  - docker

before_install:
  - docker build -t rybalka/docker-rect -f Dockerfile.dev .

script:    
  - docker run rybalka/docker-rect npm run test -- --coverage 

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-063687387139"
  bucket_path: "docker-react"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY  
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
